### ISSUE TITLE
http:// requests no longer work with hxssl

### ISSUE THREAD

**Issue by jasononeil** [tong/hxssl#26]
Hi,

With Ubuntu 12.04, 64 bit:

HTTPS, with lib (works)

```
-lib hxssl
var h = new haxe.Http("https://google.com/");
h.onData = function(d) trace(d);
h.onError = function(d) trace(d);
h.onStatus = function(d) trace(d);
h.request(false);
```

HTTP, with lib (**fails**)

```
-lib hxssl
var h = new haxe.Http("http://google.com/");
h.onData = function(d) trace(d);
h.onError = function(d) trace(d); // An unknown error has occurred.
h.onStatus = function(d) trace(d);
h.request(false);
```

HTTP, without lib (works)

```
var h = new haxe.Http("http://google.com/");
h.onData = function(d) trace(d);
h.onError = function(d) trace(d);
h.onStatus = function(d) trace(d);
h.request(false);
```

I've tried it both on my development machine and on my VPS (over in Europe somewhere), they have similar OS setups but completely different network/firewall etc, same problem.  Any idea where to start debugging, or for a workaround?  

I want to make remoting requests from one haxe server to another, which uses haxe.Http.  In development I use http, in production I use https.

**Comment by lexoyo** [comment]
Hello
I have this exact same issue as described initially by @jasononeil 
And [this fix](https://github.com/HaxeFoundation/haxe/commit/b8a98987586a83900db54463eee66299c715cfb9) seems to have been removed from the [Http class](https://github.com/Blank101/haxe/blob/development/std/haxe/Http.hx#L415)
Is it me or the problem is back?

**Comment by lexoyo** [comment]
I am on ubuntu 15.10 with haxe 3.3.0

**Comment by Blank101** [comment]
@lexoyo You are referencing my forked repository, not the official Haxe. Make sure you are using the git version of hxssl. The one on haxelib is way out of date.

**Comment by lexoyo** [comment]
Hi @Blank101 
Thank you for your quick answer
The git repo has a newer version indeed and it seems to fix my issue, thank you
