### ISSUE TITLE
Could not load module hxssl@hxssl_SSL_recv__4

### ISSUE THREAD

**Issue by hopewise** [tong/hxssl#27]
I have purchased a certificate from DNSimple, and I have added it to my website hosted by heroku: https://dcaclab.com/

When I target windows, I set the parameters of req like this:

var req;
req = new haxe.Http('https://www.dcaclab.com/activate.json'); 
req.certFolder = "assets/ssl/certs/";
req.certFile = "assets/ssl/certs/purchased_certificate.crt";

in project.xml:

```
<haxelib name="hxssl"/>
<assets path="Assets" rename="assets" include="*" exclude="openfl.svg" />
```

As I am putting my purchased_certificate.crt in assets folder, I get this error:

```
Could not load module hxssl@hxssl_SSL_recv__4
```

Any idea please?

**Comment by thomasuster** [comment]
@hopewise Did you ever get hxssl working on android / iOS?

**Comment by hopewise** [comment]
No.. I didn't this library then, I've used the native method of haxe as I
remember..
