### ISSUE TITLE
Can't hit https://api.github.com via Neko

### ISSUE THREAD

**Issue by mikestead** [tong/hxssl#34]
Hi, i'm trying to play with the github api via neko but can't seem to hit any of its endpoints.
```
var loader = new haxe.Http("https://api.github.com");
loader.setHeader("Accept", "application/vnd.github.v3+json");
loader.onData = function(value:String) { trace("Success: " + value); };		
loader.onError = function(value:String) { trace("Error: " + value); };
loader.request();
```
Outputs: `Error: Custom((1) : An unknown error has occurred.)`

Using Haxe 3.1.3. I've tried using hxssl `3.0.0-alpha` and building master but no joy. Any ideas?

**Comment by Simn** [comment]
Hi Mike,

I just came across the same problem. Did you ever find a solution?

**Comment by mikestead** [comment]
Nope sorry I never did

**Comment by Blank101** [comment]
What OS?

**Comment by Simn** [comment]
Windows for me.

**Comment by mikestead** [comment]
OS X for me

**Comment by Blank101** [comment]
Have either of you tried the latest git version? A much more detailed error should be going to stderr now.

**Comment by Simn** [comment]
Yes I am on latest git.

**Comment by tjrhodes** [comment]
Hi this is happening to me too, can you confirm "Custom((1) : An unknown error has occurred.)" is an hxssl error?

@Simn @mikestead ether of you manage to fix/workaround this?

**Comment by Blank101** [comment]
Just an update on this. I believe this error is being caused by failed certificate validation for OSX and Windows. Will be able to fix once https://github.com/HaxeFoundation/haxe/pull/4569 is merged.

**Comment by Blank101** [comment]
Can someone verify newest hxssl/haxe builds fixes this problem? Travis unit tests are passing on OS X now.

**Comment by Blank101** [comment]
Think I'll just close this unless someone tells me otherwise.

**Comment by Atry** [comment]
It became a `Error:  Eof` for Haxe 3.2.1 and hxssl master branch
