### ISSUE TITLE
Socket don't work on neko / windows for non secure url

### ISSUE THREAD

**Issue by sebpatu** [tong/hxssl#37]
Hi
I used this lib with munit, which use a localhost neko server.
the connection is not secured: http://localhost/ and the Http request gave me the errored result 
"An unknown error has occurred"

in Http.customRequest
why do you use
			} else {
				#if hxssl
				sock = new sys.ssl.Socket();
				#else
				sock = new sys.net.Socket();
				#end
			}
in default case not secure, its better to keep the default standard lib code even if hxssl is linked.

thanks

**Comment by Blank101** [comment]
Are you using the latest git version? This problem should be solved.

**Comment by sebpatu** [comment]
Le 03/02/2015 05:21, Sam a écrit :
>
> Are you using the latest git version? This problem should be solved.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/tong/hxssl/issues/37#issuecomment-72590411>.
>
I' using the latests version from haxelib

**Comment by Blank101** [comment]
That version is broken for http. Update to the git version, and it should be fixed.

**Comment by Blank101** [comment]
I'm assuming this was the problem, so I'll close.
