### ISSUE TITLE
Failed to load library 

### ISSUE THREAD

**Issue by MatthijsKamstra** [tong/hxssl#40]
I am getting this error with Neko target, even with this simple example https://github.com/tong/hxssl/tree/master/examples/03-https
 
```
Called from sys.ssl._Socket.SocketInput::socket_recv_char line 68
Uncaught exception - load.c(237) : Failed to load library : hxssl.ndll (dlopen(hxssl.ndll, 1): image not found)
```
On osx with
hxssl version:  3.0.0-alpha

**Comment by Blank101** [comment]
Looks like hxssl.ndll is not in your library path. You will need to copy or link the Mac ndll to a library directory. I'm not familiar with Mac, so I'm not sure which directory this would be.

**Comment by MatthijsKamstra** [comment]
Hi @Blank101, 
thx for responding!
You are talking about this directory: https://github.com/tong/hxssl/tree/master/ndll
And this is automatically installed via haxelib.
So I am not sure what I need to do besides adding it to my build.xml.
```
<haxelib name="hxssl" />
```
Is this problem related to my haxe version: Haxe Compiler 3.1.3?

I have tried to rebuild the lib 
```
lime rebuild hxssl ios
lime rebuild hxssl neko
``` 
but it didn't seem to have any effect.

**Comment by Blank101** [comment]
Ah, wasn't aware you were using OpenFL. I don't use OpenFL, so my knowledge of how it works is very limited. You may want to talk to the OpenFL people for this as this doesn't seem to be a hxssl issue.

**Comment by MatthijsKamstra** [comment]
Hi again, 

I can confirm it has something to do with Openfl.
The same code works fine with a .hxml buil.

thx

**Comment by MatthijsKamstra** [comment]
I have no idea what I changed, but suddenly it works in Openfl as well.
Except Neko target; it crashes

Tried to add it in the build.xml
```
<ndll name="hxssl" haxelib="hxssl" />
```
but when I removed it again, it still works with an Mac target...
