### ISSUE TITLE
Replace crypto functions with existing Haxe ones

### ISSUE THREAD

**Issue by Blank101** [tong/hxssl#42]
I see a bunch of hash functions in sys.crypto that exist in haxe.crypto under std. Is there any reason we shouldn't be using the std lib ones?

**Comment by tong** [comment]
Trust, performance, comparison, testing, ..
Not sure if we should remove them.

**Comment by Blank101** [comment]
Okay that's fine. I'll re-add the broken unit tests for these and look into fixing.
