### ISSUE TITLE
Travis Broken with new hxcpp setup

### ISSUE THREAD

**Issue by Blank101** [tong/hxssl#46]
Need to fix travis. It's erroring out on the build step for hxcpp.

**Comment by Blank101** [comment]
@hughsando I'm attempting to build openssl with your new script and am running into a problem with Travis-CI on Linux 64bit. I've followed the instructions you put in the readme, but the build is failing as you can see here: https://travis-ci.org/Blank101/hxssl/builds/62181865 . Looks like the problem is a missing file in openssl on line 912. Any ideas with this?

**Comment by hughsando** [comment]
I would expect the

cd openssl/project; neko build.n;


comand to run for much longer and generate a ton of output.  The linux port
may need to tweaking too, so I will see if I can crank up my linux
environment and work out what is going on.

**Comment by Blank101** [comment]
Fixed with b2ae08c98775e481081489139da4e0723c696503
