### ISSUE TITLE
Socket error in linux

### ISSUE THREAD

**Issue by er453r** [tong/hxssl#49]
Hi, With the newest version  from Git I get the following error:

    haxelib/hxssl/git/sys/ssl/Socket.hx:173: characters 21-30 : sys.net.Host has no field host

Tested on Linux -m64 with haxe 3.2.1

**Comment by tong** [comment]
Haxe 3.2.1 changed sys.net.Host.host to sys.net.Host.toString.
Should be fixed with b1c8110.

**Comment by Blank101** [comment]
Other way around actually. I added sys.net.Host.host to Haxe 11 days ago: https://github.com/HaxeFoundation/haxe/pull/4569 . It's still in development branch and not in a release yet. Hopefully it will be available in 3.2.2. Host.toString() is not the same as it returns the IP. I think .reverse() is the next best alternative, but it's still going to have issues until Host.host is released.

**Comment by Blank101** [comment]
Made a small correction in 5097ce7. Try now.

**Comment by tong** [comment]
Uups. Sorry+Thanks.
