### ISSUE TITLE
Deprecated...but only in development branch of haxe

### ISSUE THREAD

**Issue by IBwWG** [tong/hxssl#57]
For those of us running stable haxe 3.2.1, I'm not sure what the options are...haxe.Http refers you to hxssl, which then says it's deprecated.  I realize this is an in-between time, but is there no other option?  3.3.0 may require changes to my code base.  There are [these directions](http://r4stl1n.github.io/2015/07/30/Programming-Compiling_HXSSL_For_Win10.html), should they be used with haxe 3.2.1?

**Comment by Blank101** [comment]
I would use the latest git hxssl for < 3.3.0. The haxelib version is way out of date.

**Comment by IBwWG** [comment]
OK, but otherwise...this isn't actually deprecated then?  Updated 20 days ago...?

**Comment by Blank101** [comment]
It is depreciated for the newest version of Haxe, but it still should work fine for older versions.

**Comment by IBwWG** [comment]
Mind if I PR the readme then?  At least until the newest version is out of RC?

**Comment by hexonaut** [comment]
I added a clarification in the depreciation notice.

**Comment by IBwWG** [comment]
Thanks muchly, this will help newcomers a lot, I think :)
